#!/usr/bin/env bash
# ──────────────────────────────────────────────────────────────────────────
#  memory kit — one-command install / attach for terminal AI sessions
#
#  Branding (BRAND / CLI_NAME / ENV_FILE / MARKER) comes from kit.conf, so the
#  AXE and IMI kits share this script verbatim. Wires the memory layer into
#  your shell + Claude Code so every new session auto-recalls continued context
#  and the model knows to save:
#    1. writes <ENV_FILE>  (your key + PATH + per-session id, chmod 600)
#    2. sources it from your shell profile (idempotent marked block)
#    3. installs the SessionStart hook into ~/.claude/settings.json (auto-recall)
#    4. drops the "<BRAND> Memory protocol" into ~/.claude/CLAUDE.md (auto-save)
#
#  Usage:
#    ./install.sh                      # prompts for your key if none in the env
#    AXE_MEMORY_KEY=bnk_... ./install.sh   # (IMI_MEMORY_KEY=... for the IMI kit)
#    AXE_API_KEY=bnk_... ./install.sh      # also accepted as a fallback
#    ./install.sh --uninstall          # removes everything above
# ──────────────────────────────────────────────────────────────────────────
set -euo pipefail

# Resolve the kit dir (this script's location), following symlinks.
SRC="${BASH_SOURCE[0]}"
while [ -h "$SRC" ]; do DIR="$(cd -P "$(dirname "$SRC")" && pwd)"; SRC="$(readlink "$SRC")"; [[ $SRC != /* ]] && SRC="$DIR/$SRC"; done
KIT_DIR="$(cd -P "$(dirname "$SRC")" && pwd)"

# ── Branding (the only per-kit difference) ──
# shellcheck disable=SC1091
[ -f "$KIT_DIR/kit.conf" ] && source "$KIT_DIR/kit.conf"
: "${BRAND:=AXE}"; : "${CLI_NAME:=axe-memory}"; : "${MARKER:=$CLI_NAME}"
: "${ENV_FILE:=$HOME/.${CLI_NAME}.env}"

PROFILE="${ZDOTDIR:-$HOME}/.zshrc"
case "${SHELL:-}" in *bash) PROFILE="$HOME/.bashrc";; esac
SETTINGS="$HOME/.claude/settings.json"
CLAUDE_MD="$HOME/.claude/CLAUDE.md"
PYBIN="$(command -v python3 || true)"
HOOK_PATH="$KIT_DIR/hooks/session_start_memory.py"
START="# >>> $MARKER >>>"
END="# <<< $MARKER <<<"
MD_START="<!-- $MARKER:start -->"
MD_END="<!-- $MARKER:end -->"

strip_block() { # file start end
  [ -f "$1" ] || return 0
  awk -v s="$2" -v e="$3" '$0==s{f=1} $0==e{f=0;next} !f' "$1" > "$1.kittmp" && mv "$1.kittmp" "$1"
}

uninstall() {
  strip_block "$PROFILE" "$START" "$END"
  strip_block "$CLAUDE_MD" "$MD_START" "$MD_END"
  rm -f "$ENV_FILE"
  if [ -f "$SETTINGS" ] && [ -n "$PYBIN" ]; then
    SETTINGS="$SETTINGS" HOOK_PATH="$HOOK_PATH" "$PYBIN" - <<'PY'
import json,os
p=os.environ["SETTINGS"]; hook=os.environ["HOOK_PATH"]
try: d=json.load(open(p))
except Exception: raise SystemExit
ss=(d.get("hooks") or {}).get("SessionStart") or []
ss=[g for g in ss if not any(hook in h.get("command","") for h in g.get("hooks",[]))]
if ss: d["hooks"]["SessionStart"]=ss
elif "SessionStart" in d.get("hooks",{}): d["hooks"].pop("SessionStart",None)
json.dump(d,open(p,"w"),indent=2)
PY
  fi
  echo "$BRAND memory uninstalled. Open a new terminal for it to take effect."
  exit 0
}

[ "${1:-}" = "--uninstall" ] && uninstall

[ -n "$PYBIN" ] || { echo "python3 not found on PATH — required." >&2; exit 1; }

# ── Resolve + validate the key ──
# Dedicated memory-key var wins (so it can differ from an ambient AXE_API_KEY a
# tool pins to another identity), then <BRAND>_API_KEY, then plain AXE_API_KEY.
MEM_KEY_VAR="${BRAND}_MEMORY_KEY"
BRAND_KEY_VAR="${BRAND}_API_KEY"
KEY="${!MEM_KEY_VAR:-${!BRAND_KEY_VAR:-${AXE_API_KEY:-}}}"
if [ -z "$KEY" ]; then
  printf "Enter your %s memory key (bnk_...): " "$BRAND" >&2; read -r KEY
fi
WHO="$(env "$MEM_KEY_VAR=$KEY" "$PYBIN" "$KIT_DIR/$CLI_NAME" whoami 2>/dev/null || true)"
[ -n "$WHO" ] || { echo "Key rejected by the memory layer. Check your key." >&2; exit 1; }
echo "✓ identity: $WHO"

# ── 1. env file (key out of the shell rc; chmod 600) ──
umask 077
cat > "$ENV_FILE" <<EOF
# $BRAND memory — generated by install.sh. Safe to edit your key here.
export ${MEM_KEY_VAR}="$KEY"
export AXE_MEMORY_URL="${AXE_MEMORY_URL:-https://atlas.axe.observer}"
export PATH="$KIT_DIR:\$PATH"
[ -z "\${AXE_SESSION_ID:-}" ] && export AXE_SESSION_ID="\$(uuidgen 2>/dev/null || echo \$\$-\$(date +%s))"
EOF
chmod 600 "$ENV_FILE"
echo "✓ wrote $ENV_FILE"

# ── 2. source it from the shell profile (idempotent) ──
strip_block "$PROFILE" "$START" "$END"
{ echo "$START"; echo "[ -f \"$ENV_FILE\" ] && source \"$ENV_FILE\""; echo "$END"; } >> "$PROFILE"
echo "✓ wired $PROFILE"

# ── 3. SessionStart hook → auto-recall in Claude Code ──
mkdir -p "$(dirname "$SETTINGS")"
HOOK_CMD="$PYBIN $HOOK_PATH"
SETTINGS="$SETTINGS" HOOK_CMD="$HOOK_CMD" HOOK_PATH="$HOOK_PATH" "$PYBIN" - <<'PY'
import json,os
p=os.environ["SETTINGS"]; cmd=os.environ["HOOK_CMD"]; hook=os.environ["HOOK_PATH"]
d={}
if os.path.exists(p):
    try: d=json.load(open(p))
    except Exception: d={}
ss=d.setdefault("hooks",{}).setdefault("SessionStart",[])
if not any(hook in h.get("command","") for g in ss for h in g.get("hooks",[])):
    ss.append({"hooks":[{"type":"command","command":cmd}]})
json.dump(d,open(p,"w"),indent=2)
PY
echo "✓ installed SessionStart hook in $SETTINGS"

# ── 4. the protocol block → tells the model to recall/save ──
strip_block "$CLAUDE_MD" "$MD_START" "$MD_END"
mkdir -p "$(dirname "$CLAUDE_MD")"
cat >> "$CLAUDE_MD" <<EOF
$MD_START
## $BRAND Memory protocol
This machine shares continued context through the $BRAND memory layer (\`$CLI_NAME\`).
- At the start of a task, run \`$CLI_NAME recall\` (or \`$CLI_NAME search <kw>\`) and treat results as prior context.
- When you make a decision or learn something non-obvious, save it: \`$CLI_NAME save "<1-2 sentences>" --kind decision --tags area\`.
- Saves are private to your sessions by default; add \`--share\` to put it in your team pool.
$MD_END
EOF
echo "✓ added protocol to $CLAUDE_MD"

echo ""
echo "Done. $BRAND memory is attached as $WHO."
echo "→ run:  source \"$ENV_FILE\"   (or open a new terminal)"
echo "→ then: $CLI_NAME recall"
